#
# This is the Snakemake configuration file that specifies paths and 
# and options for the mapping pipeline, adapted from WASP
#

{
    # py2 is a hack so that python2 scripts can be called
    # by snakemake (which is written in python3). The value should
    # be a command to do whatever is needed to setup a python2 environment and
    # call the python2 interpreter. Depending on your system configuration,
    # this might involve setting the PATH environment variable or
    # just calling python2
    ##"py2" : "PATH=$HOME/anaconda2/bin:$PATH; python ",

    # directory containing scripts
    "scripts_dir" : "/home/ev250/emedlab/snake-pipe",

    # directory to write all output data files to
    "output_dir" :  "/mrc-bsu/scratch/ev250/emedlab/RNA",

    # path to STAR
    "STAR" : "/mrc-bsu/scratch/ev250/bin/STAR/source/STAR",

    # path to file to make STAR indices
    "ref_fasta" : "/home/ev250/rds/hpc-work/reference_genome/built37/Homo_sapiens.GRCh37.dna.primary_assembly.fa",

    "ref_gtf" :  "/home/ev250/rds/hpc-work/reference_genome/built37/Homo_sapiens.GRCh37.87.gtf",

    "indices" : "/mrc-bsu/scratch/ev250/reference_genome/built37/indices",

    # path to save file for exon by gene rds object to use for counting reads

    "ebg" : "/mrc-bsu/scratch/ev250/EGEUV1/quant/RNA_counts/b37_ebg.rds",

    # location of chromInfo file containing chromosome names and lengths
    # (can be downloaded from UCSC genome browser)
    #"chrom_info" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/chromInfo.hg19.txt",

    # directory to read VCF files from (used to write SNP input files)
    #"vcf_dir" : "/iblm/netapp/home/gmcvicker/data1/external/1000Genomes/GRC37/20130502",

    # OLD way: directory to write SNP plain text input files to
    #"snp_dir" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/genotypes/snps",

    # directory to write SNP HDF5 input files to
    #snp_h5_dir : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/genotypes/snp_h5",

    # path to samtools
    #"samtools" : "/iblm/netapp/home/gmcvicker/anaconda2/bin/samtools",

    # path to bowtie2 aligner
    #"bowtie2" : "/iblm/netapp/home/gmcvicker/anaconda2/bin/bowtie2",

    # prefix for bowtie2 reference genome index
    #"bowtie2_index" : "/iblm/netapp/data1/external/GRC37/combined/bowtie2_index/hg37",

    # sample file containing sample names and paths to fastq files
    "sample_file" : "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/RA.csv"
}
