#
# This is the Snakemake configuration file that specifies paths and
# and options for the mapping pipeline, adapted from WASP
#
#"bcftools view -i'ID=@{input[0]}' {input[1]} bgzip -c >  {output[0]} "

{
    # py2 is a hack so that python2 scripts can be called
    # by snakemake (which is written in python3). The value should
    # be a command to do whatever is needed to setup a python2 environment and
    # call the python2 interpreter. Depending on your system configuration,
    # this might involve setting the PATH environment variable or
    # just calling python2
    ##"py2" : "PATH=$HOME/anaconda2/bin:$PATH; python ",

    # directory containing scripts
    "scripts_dir" : "/home/kgoldmann/Documents/peac/",

    # directory to write all output data files to
    "output_dir" :  "/home/kgoldmann/Documents/PEAC_eqtl/Outputs",

    # path to STAR
    "STAR" : "/home/kgoldmann/Applications/STAR/source/STAR",

    # path to file to make STAR indices
    # ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz
    "ref_fasta" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/Reference/GRCh37/Homo_sapiens.GRCh37.dna.primary_assembly.fa",

    # ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz
    "ref_gtf" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/Reference/GRCh37/Homo_sapiens.GRCh37.87.gtf",
    "indices" : "/home/kgoldmann/Documents/PEAC_eqtl/Outputs/indices",

    # path to save file for exon by gene rds object to use for counting reads, or path to file if already made.

    "ebg" : "/home/kgoldmann/Documents/PEAC_eqtl/Outputs/b37_ebg.rds",

    # filter read cut-off for total gene counts

    "filter": 100,

    # sample file containing sample names and paths to fastq files
    "sample_file" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/RA.csv",

    #"samples": "/home/kgoldmann/NAS/RNASEQ/PEAC_RawData/SAM9103822_R1.fastq.gz",

    # sample file with metadata for peac study
    "sample_meta": "/home/kgoldmann/Documents/PEAC_eqtl/Outputs/PEAC_eth.txt",

    # file containing names and paths to vcf with genotype info file (exclude index)
    "geno_vcf" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/vcf_list.txt",
    "geno_vcf2" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/vcf_list2.txt",

    # file containing names and paths to reference panel bcf.gz
    # ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/bcf_files/
    "ref_bcf" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/Reference/refPanel_list.txt",

    # file containing names and paths to reference panel legend.gz
    # https://mathgen.stats.ox.ac.uk/impute/ALL_1000G_phase1integrated_v3_annotated_legends.tgz
    "ref_legend" : "/home/kgoldmann/Documents/PEAC_eqtl/Data/Reference/refPanel_leg_list.txt",

    # total number of PCs and PEER factors to use in Matrixqtl
    "N factors" : 10
}
