#
# This is the Snakemake configuration file that specifies paths and 
# and options for the mapping pipeline, adapted from WASP
#

{
    # py2 is a hack so that python2 scripts can be called
    # by snakemake (which is written in python3). The value should
    # be a command to do whatever is needed to setup a python2 environment and
    # call the python2 interpreter. Depending on your system configuration,
    # this might involve setting the PATH environment variable or
    # just calling python2
    ##"py2" : "PATH=$HOME/anaconda2/bin:$PATH; python ",

    # directory containing scripts
    "scripts_dir" : "/home/ev250/emedlab/snake-pipe",

    # directory to write all output data files to
    "output_dir" :  "/mrc-bsu/scratch/ev250/emedlab/RNA",

    # path to STAR
    "STAR" : "/mrc-bsu/scratch/ev250/bin/STAR/source/STAR",

    # path to file to make STAR indices
    "ref_fasta" : "/home/ev250/rds/hpc-work/reference_genome/built37/Homo_sapiens.GRCh37.dna.primary_assembly.fa",

    "ref_gtf" :  "/home/ev250/rds/hpc-work/reference_genome/built37/Homo_sapiens.GRCh37.87.gtf",
    "indices" : "/mrc-bsu/scratch/ev250/reference_genome/built37/indices",

    # path to save file for exon by gene rds object to use for counting reads, or path to file if already made.

    "ebg" : "/mrc-bsu/scratch/ev250/EGEUV1/quant/RNA_counts/b37_ebg.rds",

    # filter read cut-off for total gene counts
    
    "filter": 100,

    # sample file containing sample names and paths to fastq files
    "sample_file" : "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/RA.csv",

    # sample file with metadata por peac study
    "sample_meta": "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/PEAC_eth.txt",

    # file containing names and paths to vcf with genotype info file (exclude index)
    "geno_vcf" : "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/vcf_list.txt",

    # file containing names and paths to reference panel bcf.gz
    "ref_bcf" : "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/refPanel_list.txt",

    # file containing names and paths to reference panel legend.gz
    "ref_legend" : "/mrc-bsu/scratch/ev250/emedlab/RNA/objects/refPanel_leg_list.txt",

    # total number of PCs and PEER factors to use in Matrixqtl
    "N factors" : 10
}


